### ISSUE TITLE
cannot load 2 images at once 

### ISSUE THREAD

**Issue by jdadgebogh** [koki10190/beezle#2]
![IMG_0933](https://github.com/koki10190/beezle/assets/139131771/6ce52d36-3ca2-4d4e-80e0-6f66fd006287)

doesn’t show 2 images (there is also supposed to be text between the two)

**Comment by koki10190** [comment]
what

**Comment by jdadgebogh** [comment]
i loaded 2 images… they aint not loading.

**Comment by jdadgebogh** [comment]
i mean like they dint show its just that black thing

**Comment by koki10190** [comment]
Fixed this issue
