### ISSUE TITLE
Can't return to posts through replies

### ISSUE THREAD

**Issue by Bonkthedummy** [koki10190/beezle#4]
Whenever you click the "Replying From" bit on a post, it just...does nothing. No idea why. It just does.
Could be mobile only, who knows.

**Comment by koki10190** [comment]
This is an easy fix, consider it fixed

**Comment by koki10190** [comment]
This is an easy fix consider it fixed.

**Comment by koki10190** [comment]
This is an easy fix consider it fixed.

**Comment by koki10190** [comment]
This is an easy fix, consider it fixed
