### ISSUE TITLE
privacy & terms broken

### ISSUE THREAD

**Issue by squoggyy** [koki10190/beezle#7]
redirects to a blank page 
"If you're the developer of this page
Check out the docs to get [help with this error](https://ngrok.com/docs/errors/err_ngrok_3200).

If you're a visitor of this page
Wait a few minutes and refresh the page. If that still doesn't work, please contact the developer of this page for more information."

**Comment by koki10190** [comment]
Never noticed this lol, consider it fixed in the next update
